##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C menu
	make -C sokoban
	make -C nibbler
	make -C pacman
	make -C qix

$(NAME):
	make -C menu
	make -C sokoban
	make -C nibbler
	make -C pacman
	make -C qix

clean:
	make -C menu clean
	make -C sokoban clean
	make -C nibbler clean
	make -C pacman clean
	make -C qix clean

fclean:
	make -C menu fclean
	make -C sokoban fclean
	make -C nibbler fclean
	make -C pacman fclean
	make -C qix fclean

re:	fclean all

.PHONY: fclean all clean re tests_run
