##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

all:
	make -C sokoban

$(NAME):
	make -C sokoban

clean:
	make -C sokoban clean

fclean: clean
	make -C sokoban fclean

re:	fclean all

.PHONY: fclean all clean re tests_run
